# Generated by Django 3.2.2 on 2021-05-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=5)),
                ('dbname', models.CharField(max_length=20)),
                ('dbusr', models.CharField(max_length=100)),
                ('dbpass', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=100)),
            ],
        ),
    ]
